### ISSUE TITLE
fix pydyf version

### ISSUE THREAD

**Issue by vchalmel** [ljpengelen/markdown-to-pdf#15]
Hello, pydyf 0.11 breaks pdf generation, you can add pydyf==0.10.0 in the Dockerfile pip install cmd to avoid it.

(c.f. https://github.com/Kozea/WeasyPrint/issues/2204 for similar dependancy issue in another project)

**Comment by vchalmel** [comment]
c.f. https://github.com/ljpengelen/markdown-to-pdf/pull/16

**Comment by J1Loop** [comment]
> Hello, pydyf 0.11 breaks pdf generation, you can add pydyf==0.10.0 in the Dockerfile pip install cmd to avoid it.
> 
> (c.f. [Kozea/WeasyPrint#2204](https://github.com/Kozea/WeasyPrint/issues/2204) for similar dependancy issue in another project)

Can confirm this fixes the issue for me in various projects.
