### ISSUE TITLE
Resizing png

### ISSUE THREAD

**Issue by davidfurrer** [ljpengelen/markdown-to-pdf#2]
I have a markdown file that looks like this:

```
# report title

| symbol        | chart          | 
| ------------- |-------------|
|  A                 | ![](A_chart.png)| 
|  B                 | ![](B_chart.png)| 
```

as a css file i use:

```
@page {
  margin-top: 3cm;
  size: A4;
  }

html {
  font-family: system-ui;
  font-size: 15px;
  line-height: 1.5;
}
/* 
```

The output pdf looks like this:
![image](https://user-images.githubusercontent.com/15343123/93340108-acd34d80-f82c-11ea-9946-317dca8e58d2.png)

Any tips on how to resize pngs?

**Comment by ljpengelen** [comment]
Hi @davidfurrer,

I only just noticed that you asked this question, so you may have already solved this. Anyway, I'd try to resize the images like I would on a website. I'd give them a width or a max-width.

```
img {
  max-width: 10cm;
}
```
